### ISSUE TITLE
java.lang.NoSuchMethodError: MCL.run and MCL$.train

### ISSUE THREAD

**Issue by peppoS37** [joandre/MCL_spark#16]
Hi, I imported this library into the Databricks cluster, I tried running the run and train methods but did not find them. I'm desperate and tired, can you tell me what the problem is to you?

**Comment by joandre** [comment]
Hi, can you give me more details (config, spark version, MCL release or compiled version, ...)

**Comment by peppoS37** [comment]
-Spark version: 2.1.1
-Scala 2.10
-MCL_spark-1.0.0-s_2.10.jar
-Cloud communities Databricks

**Comment by joandre** [comment]
The first release only work for Spark 1.6.2. The current code on the repo can be compiled for Spark 2.0.1. Perhaps I will update the repo so the package works on Spark 2.1.x but I won't make a new release until we have corrected this [issue](https://github.com/joandre/MCL_spark/issues/10).

**Comment by peppoS37** [comment]
Perfect, thanks!!! ^^
